jwt:
  secret: ReplaceWithAStrongSecretKeyAtLeast32CharsLong!

spring:
  cloud:
    gateway:
        routes:
            - id: user-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/auth/**, /api/users/**
              filters:
                - name: JwtAuthenticationFilter
                  args:
                    required: false
            - id: product-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/products/**
              filters:
                - name: JwtAuthenticationFilter
            - id: order-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/orders/**
              filters:
                - name: JwtAuthenticationFilter
        discovery:
            locator:
              enabled: true
              lower-case-service-id: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/